// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkctgjieuxgqrfleuqez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrY3RnamlldXhncXJmbGV1cWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzODczMDAsImV4cCI6MjA1NTk2MzMwMH0.LDYFapWKKPlT60q74DfysSrqNRhqYE4VIorxh4nyaX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);